version: 2
jobs:
  build:
    environment:
      CI: false
    docker:
      - image: circleci/node:8.10
    working_directory: ~/amt-checklist
    steps:
      - checkout
      - run:
          name: Install dependencies of Web Admin
          command: |
            cd web-admin
            # ls -ltr
            yarn install
      - run:
          name: Building Web Admin
          command: |
            cd web-admin
            yarn build
      - save_cache:
          key: v1-build-web-admin-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - build
  # deploy:
  #   docker:
  #     - image: google/cloud-sdk
  #   environment:
  #     - PROJECT_NAME: 'my-app'
  #     - GOOGLE_PROJECT_ID: 'xxx'
  #     - GOOGLE_COMPUTE_ZONE: 'asia-southeast1-b'
  #     - GOOGLE_CLUSTER_NAME: 'cluster-1'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      # - deploy:
      # requires:
      # - build
